### PR TITLE
Icon scaling and multiple ping icons

### LINKED ISSUE #10: [Feature Request] Customizable ping icons
- Add a texture to ping icon
- Add an icon size slider in mod settings

For example, I want the default ping to look like this:

This result can be achieved by modifying size and texture

### PR DESCRIPTION
**Pull request by nils-keller-dev**
Closes #10 

This is my first time modding Minecraft and also the first time I've written Java code in years, so please bear with me.

This PR adds a new option for scaling the Ping icon and an option for cycling through a few pre-made icons.
To achieve this, I had to load the icon as a texture instead of drawing it directly using `ctx.fill`.

I have also taken into consideration that the icons for items should be larger when the "Item Icons" option is enabled.

The four icons I have added are more of a suggestion, and I'm open to feedback and ideas for new icons.

One thing to consider is that since we are now loading the icons from image files, they don't look as polished as when drawn directly with `ctx.fill`. However, I think it is only noticeable upon close inspection. Maybe there's even a way to circumvent this (with anti-aliasing?) but I could not find a way.

Also, I have set the maximum icon size in the options to 32 pixels and I'm unsure if this is a good value.
The dimensions of the image files don't matter. I created the first three in 32x32 pixels and the last one in 10x10 pixels.

Let me know what I can improve!

image
image

### CODE REVIEW

**Comment by LukenSkyne** [comment]
Thanks for your help!

A quick remark: we probably want to merge into the 1.18.2 branch, since it is the most convenient flow to migrate features for all versions (1.18.2 is now the default branch too). We'll get back to this later!

### The new scaling option:
Previously, the UI scale was used for the icon & text sizing, it is a great addition to be able to adjust the scale further.

What I am personally missing when I'm able to tweak the icon size is the option for text scale. This should probably scale with the icons and not be separated, though.

### The custom texture approach:
Using textures instead of primitives for rendering the icons is something that I tried early on and wasn't satisfied with. I think it's a good idea to allow for customization, but the feature shouldn't mess with the default icon quality.

I also think that we only need to provide one custom icon and let players change the texture through resource packs (and toggle between "default" and "custom" in the settings).

For custom textures to work with half transparent pixels, we should also toggle alpha blending with `RenderSystem.enableBlend()` and `RenderSystem.disableBlend()` for the draw calls (in-game and settings screen).

What do you think?

**Comment by nils-keller-dev** [comment]
Thank you for the feedback!
I can make a new PR for 1.18.2, no problem.

## Icon scale
I actually accidentally scaled the text with the icon at one point during developing so that won't be a problem either.

## Custom textures
Allowing the custom textures via resource packs is a great idea, I didn't think of that!
Do you know how I can accomplish that?

Also, thanks for the tip about `RenderSystem.enableBlend()`, I will look into that.

Unfortunately I won't have much time to work on this the next few days, but I will see what I can do.

**Comment by LukenSkyne** [comment]
Sure! You are probably right, a new PR would be the easiest way to target another version.

Support for resource packs comes out of the box for anything in the `resources/` folder afaik, so it is already possible to change the icons in your branch with a resource pack structured like this:
```
Example Resource Pack/
├─ pack.mcmeta
├─ assets/
│  ├─ ping-wheel/
│  │  ├─ textures/
│  │  │  ├─ ping/
│  │  │  │  ├─ icon_3.png
```
Though, I would prefer to keep only one `ping.png` and move it up into the `textures/` directly for simplicity.

Do you think the idea to keep the default icon rendered the old way is something you wanna try?

Something I forgot in my first response: I also noticed that you used emojis for your commits to keep the history consistent, which is appreciated! For future reference, keep in mind that [gitmoji](https://gitmoji.dev/) has a rough overview of what different emojis mean. For example `:bento:` (:bento:) to add new textures or assets.

And don't worry about time!

**Comment by nils-keller-dev** [comment]
Thank you, I will try out your suggestion regarding the resource pack.

And I will definitely keep the old rendering for the default icon.

Also thank you for directing me to gitmoji. I just noticed you were using emojis so I did too, without knowing of a convention 😄

**Comment by nils-keller-dev** [comment]
I created [a new PR](https://github.com/LukenSkyne/Minecraft-Ping-Wheel/pull/18), so this one is obsolete

**Pull request closed without merging**
