### PR TITLE
Create fr_fr.json

### PR DESCRIPTION
**Pull request by acorsicanfrog**

### CODE REVIEW

**Comment by LukenSkyne** [comment]
Hey!
Thanks for helping out with the translation of Ping Wheel!

The text for `ping-wheel.settings.nameLabelForced` seems to be a bit long, as you can see in the bottom left:

image

I would appreciate a lot if you tried to find a shorter variant for it. If necessary, we can keep it this way for better understanding.

**Comment by acorsicanfrog** [comment]
Hi!

Well you were quick haha

Alright you can remove the 'Toujours' word, will work fine 

Not sure how to edit something I already pushed?

**Comment by LukenSkyne** [comment]
You can just change the file again in your branch/fork and then push it!
In the main branch, it will be squashed to a single commit anyways so don't worry about having multiple commits

**Review by acorsicanfrog — COMMENTED** [review]
Shortened the 'nameLabelForced' setting translation

**Comment by LukenSkyne** [comment]
Alright thank you! ❤️

**Pull request merged**
